// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spt.priceofriceservicerequestor.base;

import com.spt.priceofriceservicerequestor.base.BaseEntity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BaseEntity_Roo_Configurable {
    
    declare @type: BaseEntity: @Configurable;
    
}
